version: "3.9"

services:
  # Django app
  app:
    build:
      context: .
    ports:
      - 8001:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    env_file:
      - ./.env
    container_name: django_api_forwardingcr
    depends_on: 
      - db
    restart: always

  
  # Database
  db:
    image: mysql:8
    volumes:
      - ./database/lib:/var/lib/mysql
    env_file:
      - ./.env
    container_name: mysql_db_api_forwardingcr
    ports:
      - 3307:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--log-error-verbosity=1']


  