# Generated by Django 4.2.5 on 2025-04-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50)),
                ('date_time', models.DateField()),
                ('expiration_date', models.DateField()),
                ('contact_person', models.CharField(max_length=100)),
                ('estado_cotizacion', models.BooleanField(default=True)),
                ('subtotal_cotizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_13', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cotizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_volume', models.CharField(max_length=50)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_boolean', models.BooleanField(default=False)),
                ('price_service', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_service', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_servicio', to='api_forwardingcr.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details', models.TextField()),
                ('delivery_address', models.TextField()),
                ('type_of_movement', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_envio', to='api_forwardingcr.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='chargeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_charges', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_servicio', to='api_forwardingcr.cotizacion')),
            ],
        ),
    ]
