# Generated by Django 4.2.5 on 2025-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forwardingcr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinformation',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='serviceinformation',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='serviceinformation',
            name='largo',
        ),
        migrations.AddField(
            model_name='serviceinformation',
            name='metroCubicoVolumen',
            field=models.CharField(default='0x0x0', max_length=50),
            preserve_default=False,
        ),
    ]
