# Generated by Django 4.2.5 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forwardingcr', '0002_remove_serviceinformation_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='quotation_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
