# Generated by Django 4.2.5 on 2025-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forwardingcr', '0003_alter_cotizacion_quotation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='contact_person',
            field=models.EmailField(max_length=100),
        ),
    ]
